#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic-image
  namespace: tap-install
spec:
  tag: (@= data.values.container_image_name @)
  serviceAccount: tap-service-account
  builder:
    kind: ClusterBuilder
    name: default
  source:
    git:
      url: https://github.com/(@= data.values.github_org @)/spring-pet-clinic-eks
      revision: main