#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name:  docker-hub-registry
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
data:
  #@ docker_auth = base64.encode("{}:{}".format(data.values.docker_username, data.values.docker_password))
  #@ docker_creds = {"username": data.values.docker_username, "password": data.values.docker_password, "auth": docker_auth}
  .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.docker_registry: docker_creds}}))