version: '3'

services:
  registry:
    container_name: "kind-registry"
    image: registry:2
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      #REGISTRY_HTTP_ADDR: 0.0.0.0:443
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    restart: always
    volumes:
      - /home/snowdrop/tmp:/auth
      #- /home/snowrop/certs:/certs
