apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-buildah
spec:
  inputs:
    params:
    - default: quay.io/halkyonio/spring-boot-maven-s2i
      description: S2i base image
      name: baseImage
    - default: .
      description: The location of the path to run s2i from
      name: contextPath
    - default: .
      description: The name of the directory containing the project (maven, ...) to
        be compiled
      name: moduleDirName
    - default: "false"
      description: Verify registry certificates
      name: verifyTLS
    - default: /workspace/git
      description: Git path where project is cloned
      name: workspacePath
    resources:
    - name: git
      outputImageDir: ""
      targetPath: ""
      type: git
  outputs:
    resources:
    - name: image
      outputImageDir: /builder/home/image-outputs/image
      targetPath: ""
      type: image
  steps:
  - args:
    - bud
    - --tls-verify=${inputs.params.verifyTLS}
    - --layers
    - -f
    - /sources/Dockerfile.gen
    - -t
    - ${outputs.resources.image.url}
    - .
    command:
    - buildah
    image: quay.io/buildah/stable:v1.9.0
    name: build
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: libcontainers
    - mountPath: /sources
      name: generatedsources
    workingDir: /sources
  volumes:
  - emptyDir: {}
    name: generatedsources
  - emptyDir: {}
    name: libcontainers
