apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    tekton.dev/task: s2i-buildah
  name: test1
spec:
  inputs:
    params:
    - name: baseImage
      value: quay.io/halkyonio/spring-boot-maven-s2i
    - name: moduleDirName
      value: fruit-client-sb
    - name: contextPath
      value: .
    resources:
    - name: git
      resourceRef: {}
      resourceSpec:
        params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/rhte-eu/cmoullia.git
        type: git
  outputs:
    resources:
    - name: image
      resourceRef: {}
      resourceSpec:
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/rhtelab/fruit-client-lab
        type: image
  serviceAccount: build-bot
  taskRef:
    kind: Task
    name: s2i-buildah
  timeout: 1h0m0s