apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv016
  labels:
    build-tool: maven
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/pv016
  persistentVolumeReclaimPolicy: Recycle