apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: runtime
spec:
  serviceAccountRef:
    name: controller
    namespace: kpack
  sources:
    - image: registry.local:5000/redhat-buildpacks/quarkus-java