apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: runtime
spec:
  order:
  - group:
      - id: "io.quarkus.buildpacks.buildpack"
  serviceAccountRef:
    name: default
    namespace: demo
  stack:
    name: runtime
    kind: ClusterStack
  store:
    name: runtime
    kind: ClusterStore
  tag: "registry.local:5000/runtime"