apiVersion: v1
data:
  haSharedSecret: U1RwcHBCOHkwZVU0M2FqdQ==
  htpasswd: Y21vdWxsaWFyZDokMnkkMDUkTFRwVHJOa0ZyaEdoU1B6MFFYZEo1T0IybldBTzMybXgzbzJQWlJHSXdQY1dMSERKQW5HYWUK
kind: Secret
metadata:
  name: registry-docker-registry-secret
  namespace: default
type: Opaque