apiVersion: shipwright.io/v1alpha1
kind: BuildRun
metadata:
  name: buildpack-quarkus-buildrun-1
  namespace: demo
spec:
  serviceAccount:
    name: registry-creds
    generate: false
  buildRef:
    name: buildpack-quarkus-build