apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: spring-boot-monitoring
  name: spring-boot-monitoring
spec:
  selector:
    matchLabels:
      app: spring-boot-monitoring
  endpoints:
    - port: http
      path: "/actuator/prometheus"
      interval: "10s"
      honorLabels: false
