apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-editor
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:test
